-- Idempotent concept seed. IDs are referenced by mobile fixtures, lessons and paper manifests.
insert into concepts (id, name, asset_class, level, summary) values
 ('bond-price-yield','Bond prices and yields','rates','beginner','Bond prices and yields move inversely.'),
 ('duration','Duration','rates','intermediate','Sensitivity of a bond''s price to changes in yield.'),
 ('yield-curve','Yield curve','rates','beginner','Yields across maturities; slope signals growth and policy expectations.'),
 ('real-yields','Nominal vs real yields','rates','intermediate','Real yield = nominal yield minus expected inflation.'),
 ('cpi-surprise','Inflation (CPI) surprises','macro','beginner','Markets react to CPI relative to expectations, not the level alone.'),
 ('rate-expectations','Interest-rate expectations','macro','intermediate','Prices embed the expected path of policy rates.'),
 ('discount-rates-equities','Discount rates and equity valuation','equities','intermediate','Higher discount rates reduce the present value of future earnings.'),
 ('long-duration-equities','Long-duration growth equities','equities','advanced','Growth stocks with distant cash flows are most rate-sensitive.'),
 ('earnings-vs-guidance','Earnings vs guidance','equities','beginner','Guidance often moves prices more than the reported quarter.'),
 ('sector-rotation','Sector rotation','equities','intermediate','Capital shifts between sectors as the macro regime changes.'),
 ('usd-rate-differentials','USD and rate differentials','fx','intermediate','Currency moves reflect relative interest rates and risk appetite.'),
 ('oil-drivers','Oil price drivers','commodities','beginner','Supply, demand, inventories and geopolitics drive crude.'),
 ('gold-real-yields','Gold and real yields','commodities','intermediate','Gold tends to fall when real yields rise.'),
 ('risk-on-off','Risk-on / risk-off','cross-asset','beginner','Shifts in risk appetite move equities, bonds, USD and gold together.'),
 ('vix','Volatility and the VIX','cross-asset','beginner','The VIX measures expected 30-day S&P 500 volatility.'),
 ('correlation','Correlation','portfolio','intermediate','How assets move together; drives diversification.'),
 ('diversification','Diversification','portfolio','beginner','Spreading risk across imperfectly correlated assets.'),
 ('position-sizing','Position sizing','portfolio','intermediate','How much to risk on a view given uncertainty.'),
 ('priced-in','What is priced in','cross-asset','intermediate','Prices already reflect widely expected information.'),
 ('market-liquidity','Market liquidity','microstructure','intermediate','Ability to trade size without moving price.'),
 ('momentum-strategy','Momentum strategies','equities','advanced','Buy past winners, sell past losers.'),
 ('momentum-crashes','Momentum crashes','equities','advanced','Sharp momentum losses in panic states and market rebounds.'),
 ('market-regime','Market regimes','cross-asset','advanced','Different volatility/trend environments change strategy behavior.'),
 ('earnings-momentum','Earnings momentum','equities','advanced','Persistent earnings surprises help explain price momentum.'),
 ('underreaction-overreaction','Underreaction and overreaction','equities','advanced','Gradual information diffusion and trend-chasing create momentum then reversal.'),
 ('limits-to-arbitrage','Limits to arbitrage','microstructure','advanced','Costs and constraints stop traders from eliminating mispricing.'),
 ('liquidity-risk','Liquidity risk','microstructure','advanced','Systematic variation in liquidity is priced in returns.'),
 ('transaction-costs','Transaction costs','microstructure','intermediate','Costs that reduce realized strategy returns.'),
 ('st-morning-meeting','Morning meeting structure','sales-trading','intermediate','How to deliver a concise, prioritized market summary.')
on conflict (id) do update set name=excluded.name, level=excluded.level, summary=excluded.summary, asset_class=excluded.asset_class;

insert into concept_edges (from_id, to_id, relation) values
 ('bond-price-yield','duration','prerequisite'),
 ('bond-price-yield','yield-curve','prerequisite'),
 ('bond-price-yield','real-yields','prerequisite'),
 ('real-yields','discount-rates-equities','prerequisite'),
 ('discount-rates-equities','long-duration-equities','prerequisite'),
 ('real-yields','gold-real-yields','related'),
 ('cpi-surprise','rate-expectations','prerequisite'),
 ('momentum-strategy','momentum-crashes','prerequisite'),
 ('momentum-strategy','earnings-momentum','related'),
 ('momentum-strategy','underreaction-overreaction','related'),
 ('momentum-strategy','limits-to-arbitrage','related'),
 ('limits-to-arbitrage','liquidity-risk','related'),
 ('liquidity-risk','transaction-costs','related'),
 ('vix','market-regime','related')
on conflict do nothing;
