/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/health": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Health */
        get: operations["health_health_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/tutor/lesson": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Tutor Lesson */
        post: operations["tutor_lesson_v1_tutor_lesson_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/kb/search": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Kb Search */
        post: operations["kb_search_v1_kb_search_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/sources/{chunk_id}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Source */
        get: operations["get_source_v1_sources__chunk_id__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/quiz/preferences": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Preferences */
        get: operations["get_preferences_v1_quiz_preferences_get"];
        /** Put Preferences */
        put: operations["put_preferences_v1_quiz_preferences_put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/quiz/sessions": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Start Session */
        post: operations["start_session_v1_quiz_sessions_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/quiz/sessions/{session_id}/answers": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Answer */
        post: operations["submit_answer_v1_quiz_sessions__session_id__answers_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/quiz/sessions/{session_id}/refill": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Refill Session */
        post: operations["refill_session_v1_quiz_sessions__session_id__refill_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/quiz/sessions/{session_id}/end": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** End Session */
        post: operations["end_session_v1_quiz_sessions__session_id__end_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/learn/progress": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Learn Progress */
        get: operations["learn_progress_v1_learn_progress_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/v1/dev/fixtures/{name}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Get Fixture */
        get: operations["get_fixture_v1_dev_fixtures__name__get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** AnswerFeedback */
        AnswerFeedback: {
            /**
             * Observed
             * @enum {string}
             */
            observed: "correct" | "partial" | "incorrect";
            /** Score */
            score: number;
            /** Explanation */
            explanation: string;
            /** Strengths */
            strengths?: string[];
            /** Gaps */
            gaps?: string[];
            /** Correct Option Id */
            correct_option_id?: string | null;
            /** Review Concept Ids */
            review_concept_ids?: string[];
        };
        /** ConceptUpdate */
        ConceptUpdate: {
            /** Concept Id */
            concept_id: string;
            /**
             * Observed
             * @enum {string}
             */
            observed: "correct" | "partial" | "incorrect";
            /** Mastery Before */
            mastery_before: number;
            /** Mastery After */
            mastery_after: number;
            /** Next Review At */
            next_review_at: string;
        };
        /** EndSessionResponse */
        EndSessionResponse: {
            session: components["schemas"]["QuizSession"];
            /** Answered Count */
            answered_count: number;
            /** Correct Count */
            correct_count: number;
            /** Percent Correct */
            percent_correct: number;
            /** Weak Concept Ids */
            weak_concept_ids: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** Health */
        Health: {
            /**
             * Status
             * @enum {string}
             */
            status: "ok" | "degraded";
            /**
             * Data Mode
             * @enum {string}
             */
            data_mode: "live" | "cache" | "demo";
            /** Version */
            version: string;
            /** Checks */
            checks: {
                [key: string]: boolean;
            };
        };
        /** KbSearchRequest */
        KbSearchRequest: {
            /** Query */
            query: string;
            /**
             * Layer
             * @default foundation
             */
            layer: ("foundation" | "market") | null;
            /** Concept Ids */
            concept_ids?: string[] | null;
            /**
             * Level
             * @default advanced
             * @enum {string}
             */
            level: "beginner" | "intermediate" | "advanced";
            /**
             * K
             * @default 5
             */
            k: number;
        };
        /** LearnConcept */
        LearnConcept: {
            /** Concept Id */
            concept_id: string;
            /** Name */
            name: string;
            /** Mastery */
            mastery: number;
            /** Attempts */
            attempts: number;
            /** Next Review At */
            next_review_at?: string | null;
            /**
             * Is Focus
             * @default false
             */
            is_focus: boolean;
        };
        /** LearnProgress */
        LearnProgress: {
            /**
             * Level
             * @enum {string}
             */
            level: "beginner" | "intermediate" | "advanced";
            /** Concepts */
            concepts: components["schemas"]["LearnConcept"][];
            /** Recommended Concept Ids */
            recommended_concept_ids: string[];
            /** Weak Concept Ids */
            weak_concept_ids: string[];
            /** Strong Concept Ids */
            strong_concept_ids: string[];
            /** Due Reviews */
            due_reviews: string[];
            /** Recent Attempts */
            recent_attempts: components["schemas"]["RecentAttempt"][];
            /**
             * Streak Days
             * @default 0
             */
            streak_days: number;
            /** Recent Scores */
            recent_scores?: number[];
            /** Preferred Formats */
            preferred_formats?: ("mcq" | "case_study" | "short_answer" | "analysis")[];
            /** Custom Topics */
            custom_topics?: string[];
        };
        /** LessonResponse */
        LessonResponse: {
            lesson: components["schemas"]["TeachingLesson"];
            /** Citations */
            citations: components["schemas"]["SourceRefLite"][];
            /** Follow Up */
            follow_up: string;
            /** Mastery Updates */
            mastery_updates: components["schemas"]["ConceptUpdate"][];
            /**
             * Generated By
             * @default llm
             * @enum {string}
             */
            generated_by: "llm" | "fallback";
            retrieval?: components["schemas"]["RetrievalInfo"] | null;
        };
        /** LessonSection */
        LessonSection: {
            /**
             * Kind
             * @enum {string}
             */
            kind: "supported" | "synthesis" | "assumption" | "uncertainty";
            /** Heading */
            heading: string;
            /** Text */
            text: string;
            /** Source Ids */
            source_ids: string[];
        };
        /** MasteryDelta */
        MasteryDelta: {
            /** Concept Id */
            concept_id: string;
            /**
             * Observed
             * @enum {string}
             */
            observed: "correct" | "partial" | "incorrect";
            /** Mastery Before */
            mastery_before: number;
            /** Mastery After */
            mastery_after: number;
        };
        /** McqOptionPublic */
        McqOptionPublic: {
            /** Id */
            id: string;
            /** Text */
            text: string;
        };
        /** QuizPreferences */
        QuizPreferences: {
            /** Preferred Formats */
            preferred_formats?: ("mcq" | "case_study" | "short_answer" | "analysis")[];
            /** Preferred Concept Ids */
            preferred_concept_ids?: string[];
            /** Custom Topics */
            custom_topics?: string[];
            /**
             * Level
             * @default beginner
             * @enum {string}
             */
            level: "beginner" | "intermediate" | "advanced";
        };
        /** QuizPreferencesResponse */
        QuizPreferencesResponse: {
            preferences: components["schemas"]["QuizPreferences"];
            /** Available Formats */
            available_formats: {
                [key: string]: string;
            }[];
            /** Available Topics */
            available_topics: components["schemas"]["TopicOption"][];
        };
        /** QuizQuestionPublic */
        QuizQuestionPublic: {
            /** Id */
            id: string;
            /** Sequence */
            sequence: number;
            /**
             * Format
             * @enum {string}
             */
            format: "mcq" | "case_study" | "short_answer" | "analysis";
            /** Difficulty */
            difficulty: number;
            /** Concept Ids */
            concept_ids: string[];
            /** Custom Topic */
            custom_topic?: string | null;
            /** Prompt */
            prompt: string;
            /** Options */
            options?: components["schemas"]["McqOptionPublic"][] | null;
            /** Context */
            context?: string | null;
            /** Word Range */
            word_range?: [
                number,
                number
            ] | null;
            /** Hints */
            hints?: string[];
        };
        /** QuizSession */
        QuizSession: {
            /** Id */
            id: string;
            /**
             * Status
             * @enum {string}
             */
            status: "active" | "ended";
            /** Formats */
            formats: ("mcq" | "case_study" | "short_answer" | "analysis")[];
            /** Concept Ids */
            concept_ids: string[];
            /** Custom Topics */
            custom_topics: string[];
            /**
             * Level
             * @enum {string}
             */
            level: "beginner" | "intermediate" | "advanced";
            /** Answered Count */
            answered_count: number;
            /** Correct Count */
            correct_count: number;
            /**
             * Ready Count
             * @default 0
             */
            ready_count: number;
        };
        /** RecentAttempt */
        RecentAttempt: {
            /** Question Id */
            question_id: string;
            /**
             * Format
             * @enum {string}
             */
            format: "mcq" | "case_study" | "short_answer" | "analysis";
            /** Concept Ids */
            concept_ids: string[];
            /**
             * Observed
             * @enum {string}
             */
            observed: "correct" | "partial" | "incorrect";
            /** Score */
            score: number;
            /** Submitted At */
            submitted_at: string;
        };
        /** RefillResponse */
        RefillResponse: {
            /** Added */
            added: number;
            /** Queue Depth */
            queue_depth: number;
            session: components["schemas"]["QuizSession"];
            question?: components["schemas"]["QuizQuestionPublic"] | null;
        };
        /** RetrievalInfo */
        RetrievalInfo: {
            /** Chunks Considered */
            chunks_considered: number;
            /** Top Similarity */
            top_similarity: number | null;
            /** Sufficient */
            sufficient: boolean;
        };
        /** SearchHit */
        SearchHit: {
            /** Chunk Id */
            chunk_id: string;
            /** Document Id */
            document_id: string;
            /** Title */
            title: string;
            /** Section Path */
            section_path: string | null;
            /** Excerpt */
            excerpt: string;
            /** Similarity */
            similarity: number;
            /** Score */
            score: number;
            /** Difficulty */
            difficulty: number | null;
            /** Content Type */
            content_type: string | null;
        };
        /** SourceRef */
        SourceRef: {
            /** Source Id */
            source_id: string;
            /** Title */
            title: string;
            /** Publisher */
            publisher: string;
            /** Url */
            url?: string | null;
            /** Published At */
            published_at?: string | null;
            /** Section Path */
            section_path?: string | null;
            /** Excerpt */
            excerpt?: string | null;
            /**
             * Trust Level
             * @default 4
             */
            trust_level: number;
        };
        /** SourceRefLite */
        SourceRefLite: {
            /** Source Id */
            source_id: string;
            /** Title */
            title: string;
            /** Publisher */
            publisher: string;
            /** Url */
            url?: string | null;
            /** Chunk Id */
            chunk_id?: string | null;
            /** Section Path */
            section_path?: string | null;
            /** Excerpt */
            excerpt?: string | null;
            /** Content Type */
            content_type?: string | null;
            /** Published At */
            published_at?: string | null;
        };
        /** StartSessionRequest */
        StartSessionRequest: {
            /** Formats */
            formats: ("mcq" | "case_study" | "short_answer" | "analysis")[];
            /** Concept Ids */
            concept_ids?: string[];
            /** Custom Topics */
            custom_topics?: string[];
            /** Level */
            level?: ("beginner" | "intermediate" | "advanced") | null;
        };
        /** StartSessionResponse */
        StartSessionResponse: {
            session: components["schemas"]["QuizSession"];
            question: components["schemas"]["QuizQuestionPublic"];
            /** Queue Depth */
            queue_depth: number;
        };
        /** SubmitAnswerRequest */
        SubmitAnswerRequest: {
            /** Question Id */
            question_id: string;
            /** Answer */
            answer: {
                [key: string]: unknown;
            };
        };
        /** SubmitAnswerResponse */
        SubmitAnswerResponse: {
            /** Attempt Id */
            attempt_id: string;
            feedback: components["schemas"]["AnswerFeedback"];
            /** Mastery Updates */
            mastery_updates: components["schemas"]["MasteryDelta"][];
            next_question?: components["schemas"]["QuizQuestionPublic"] | null;
            /** Queue Depth */
            queue_depth: number;
            session: components["schemas"]["QuizSession"];
        };
        /** TeachingLesson */
        TeachingLesson: {
            /** Concept Id */
            concept_id: string;
            /**
             * Level
             * @enum {string}
             */
            level: "beginner" | "intermediate" | "advanced";
            /** Sections */
            sections: components["schemas"]["LessonSection"][];
            /** Check Question */
            check_question: string;
            /**
             * Insufficient Evidence
             * @default false
             */
            insufficient_evidence: boolean;
        };
        /** TopicOption */
        TopicOption: {
            /** Id */
            id: string;
            /** Name */
            name: string;
            /** Asset Class */
            asset_class?: string | null;
            /**
             * Level
             * @default beginner
             * @enum {string}
             */
            level: "beginner" | "intermediate" | "advanced";
            /** Summary */
            summary?: string | null;
        };
        /** TutorLessonRequest */
        TutorLessonRequest: {
            /** Concept Id */
            concept_id: string;
            /**
             * Level
             * @default beginner
             * @enum {string}
             */
            level: "beginner" | "intermediate" | "advanced";
            /** Misconception */
            misconception?: string | null;
            /** Question */
            question?: string | null;
        };
        /** UpdatePreferencesRequest */
        UpdatePreferencesRequest: {
            /** Preferred Formats */
            preferred_formats?: ("mcq" | "case_study" | "short_answer" | "analysis")[] | null;
            /** Preferred Concept Ids */
            preferred_concept_ids?: string[] | null;
            /** Custom Topics */
            custom_topics?: string[] | null;
            /** Level */
            level?: ("beginner" | "intermediate" | "advanced") | null;
        };
        /** ValidationError */
        ValidationError: {
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
            /** Input */
            input?: unknown;
            /** Context */
            ctx?: Record<string, never>;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    health_health_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["Health"];
                };
            };
        };
    };
    tutor_lesson_v1_tutor_lesson_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["TutorLessonRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LessonResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    kb_search_v1_kb_search_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["KbSearchRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SearchHit"][];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_source_v1_sources__chunk_id__get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                chunk_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SourceRef"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_preferences_v1_quiz_preferences_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizPreferencesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    put_preferences_v1_quiz_preferences_put: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["UpdatePreferencesRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["QuizPreferencesResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    start_session_v1_quiz_sessions_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["StartSessionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StartSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    submit_answer_v1_quiz_sessions__session_id__answers_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SubmitAnswerRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["SubmitAnswerResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    refill_session_v1_quiz_sessions__session_id__refill_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RefillResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    end_session_v1_quiz_sessions__session_id__end_post: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path: {
                session_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["EndSessionResponse"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    learn_progress_v1_learn_progress_get: {
        parameters: {
            query?: never;
            header?: {
                authorization?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LearnProgress"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    get_fixture_v1_dev_fixtures__name__get: {
        parameters: {
            query?: never;
            header?: never;
            path: {
                name: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": unknown;
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
}
